### ZIP File with One CSV File

orders.zip
    └── orders.csv

In [2]:
import pandas as pd

df = pd.read_csv("E:/data/Documents/Data_Engineering/Module1_Data_Source/module1-dataset/orders_single_csv.zip")

print(df.head())

   order_id  customer_id  order_date  amount     status
0         1          101  2026-04-01    1200  Completed
1         2          102  2026-04-01    2500    Pending
2         3          103  2026-04-02    1800  Completed
3         4          104  2026-04-03    3200  Cancelled
4         5          105  2026-04-03     900  Completed

In [5]:
df = pd.read_csv("E:/data/Documents/Data_Engineering/Module1_Data_Source/module1-dataset/orders_single_csv.zip", 
                 compression="zip")
df.head()

   order_id  customer_id  order_date  amount     status
0         1          101  2026-04-01    1200  Completed
1         2          102  2026-04-01    2500    Pending
2         3          103  2026-04-02    1800  Completed
3         4          104  2026-04-03    3200  Cancelled
4         5          105  2026-04-03     900  Completed

### ZIP File with Multiple Files

daily_files.zip
    ├── orders.csv
    ├── customers.csv
    └── products.csv

In [6]:
import zipfile

zip_path = "E:/data/Documents/Data_Engineering/Module1_Data_Source/module1-dataset/daily_files_multiple_csv.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    print(zip_ref.namelist())

['orders.csv', 'customers.csv', 'products.csv']

#### Reading specific file

In [9]:


with zipfile.ZipFile(zip_path, "r") as zip_ref:
    with zip_ref.open("orders.csv") as file:
        df = pd.read_csv(file)

print(df.head())

   order_id  customer_id  order_date  amount     status
0         1          101  2026-04-01    1200  Completed
1         2          102  2026-04-01    2500    Pending
2         3          103  2026-04-02    1800  Completed
3         4          104  2026-04-03    3200  Cancelled
4         5          105  2026-04-03     900  Completed

#### Reading all files

In [19]:
dataframes = {}

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    for file_name in zip_ref.namelist():
        if file_name.endswith(".csv"):
            with zip_ref.open(file_name) as file:
                dataframe_name = file_name.removesuffix(".csv")
                print(dataframe_name)
                dataframes[dataframe_name] = pd.read_csv(file)


orders_df = dataframes["orders"]
customers_df = dataframes["customers"]
products_df = dataframes["products"]

orders
customers
products

In [21]:
orders_df

   order_id  customer_id  order_date  amount     status
0         1          101  2026-04-01    1200  Completed
1         2          102  2026-04-01    2500    Pending
2         3          103  2026-04-02    1800  Completed
3         4          104  2026-04-03    3200  Cancelled
4         5          105  2026-04-03     900  Completed